[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "entry"
line_length = 88
py_version = "py38"
isort_known_first_party = ["gzcv","helpers"]
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
[tool.pysen.lint.source]
exclude_globs = ["./venv"]
